#!/usr/bin/env python
import sys, os
import json
import string

bugIds = []
commit_filepath = sys.argv[1]
dataElement = json.load(open('/home/ravi/test_folder/jsonFormat.txt'))
for data in dataElement[u'Bugs']:
	bugIds.append(data['ID'])
# print bugIds

with open(commit_filepath, 'r') as msgFile:
	commit_msg = msgFile.read()
	if not commit_msg or commit_msg is '':
		print('Enter the valid Comment.')
		sys.exit(1)
	else:
		commitTextList = commit_msg.splitlines()
		commitTextList = filter(None, commitTextList)
		for text in commitTextList:
			if not text or text is '':
				print "mismatched=="+text
				print('Bug string mismatched')
			elif text.startswith('Bug Id'):
				print "0=="+text
				text = string.replace(text,"Bug Id:", " ")
				print "2=="+text
				bugsTextList = text.split('-')
				print "Bug ID =="+bugsTextList[0].strip()
				if any(bugsTextList[0].strip() in s for s in bugIds):
					print("Proceed commit")
				else:
					bug = bugsTextList[0].strip()
					print("Bug ID: "+str(bug)+" Not found in the list! Provide the valid bug")
					sys.exit(1)
			else:
				print("\n=========Bug ID not found.==========")
				print ("Please enter the valid Bug. Abort Commit\n")
				sys.exit(1)