#!/usr/bin/env python
import sys
import os
import subprocess
import re
import urllib, json
import string
import sqlite3

def main():
    input  = sys.stdin.read()
    oldrev, newrev, refname = input.split(" ")
    separator = "----****----"
    proc = subprocess.Popen(["git", "log", "--format=%H%n%ci%n%s%b%n" + separator, oldrev + ".." +  newrev], stdout=subprocess.PIPE)
    message = proc.stdout.read()
    url = "http://172.30.36.194:8080/bugapp/read_bugs?message="+message
    response = urllib.urlopen(url)
    resultData = str(response.read())
    data = json.loads(resultData)
    resAction = data['Action']
    if resAction == 'Push':
        dataMessage = data['message']
        print('Successfully committed.')
    else:
        dataMessage = data['message']
        print('Abort commit')
        print(dataMessage)
        sys.exit(1)

main()